# Generated by Django 5.0.1 on 2024-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_customuser_age_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
